REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes

LTO_ENABLE = yes

EXTRAKEY_ENABLE = yes
OLED_ENABLE = yes
ENCODER_ENABLE = yes
#ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no
QMK_SETTINGS = no
MOUSEKEY_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
